name: Playwright CI

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Specific test file to run (e.g., tests/sample.spec.ts)'
        required: false
        default: ''
      runner:
        description: 'Select runner to use'
        required: false
        default: 'any'
        type: choice
        options:
          - any
          - machine1
          - machine2

jobs:
  playwright-tests:
    runs-on: ${{ github.event.inputs.runner == 'any' && 'self-hosted' || github.event.inputs.runner }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Configure Test User
        run: |
          Write-Host "Running on machine: $env:RUNNER_LABEL with user: $env:TEST_USER"
          
          # Check for machine-specific login file
          $configFile = "config/login-$env:RUNNER_LABEL.json"
          if (Test-Path $configFile) {
            Copy-Item $configFile -Destination "config/login.json" -Force
            Write-Host "Using configuration for $env:RUNNER_LABEL"
          } else {
            Write-Host "No specific config found for $env:RUNNER_LABEL, using default config"
          }
        shell: pwsh

      - name: Run Playwright Tests
        run: |
          if ($env:GITHUB_EVENT_INPUTS_TEST_FILE) {
            Write-Host "Running specified test file: $env:GITHUB_EVENT_INPUTS_TEST_FILE"
            npx playwright test $env:GITHUB_EVENT_INPUTS_TEST_FILE
          } else {
            Write-Host "Running all test files"
            npx playwright test
          }
        shell: pwsh

      # ...existing Allure reporting steps...